### ISSUE TITLE
Twitter Sample .apk with espresso package

### ISSUE THREAD

**Issue by ManuelWeberMway** [mway-io/Espresso#105]
Hey , 

after updating the espresso to the latest version ( detox branch! ) , I had the possibility to build an .apk file of the Twitter Sample App: 

I used this in the config.json : 

"package": {
        "default": {
            "method": "Cordova",
            "os": "Android",
            "sdk": "android-15",
            "package": "com.test.twitter",
            "activity": "Twitter",
            "mode": "release",
            "keystore": "/path/to/key/mykey.keystore",
            "keyalias": "keyname",
            "storepass": "xxx",
            "manifest": {
                "-android:versionCode": "1",
                "-android:versionName": "0.0.1",

```
            "uses-sdk": {
                "-android:minSdkVersion": "8"
            }
        },
        "autoScaleIcon": true
    }
```

and I received this error: 

/Users/myName/Documents/Espresso/package/Cordova/Android/bin/setup-icons: line 36: convert: command not found 

But if I delete the "autoScaleIcon" line , everything works right!

**Comment by 4z3** [comment]
For autoScaleIcon you have to have [ImageMagick](http://www.imagemagick.org/) (which provides the [convert](http://www.imagemagick.org/script/convert.php) command) installed.

**Comment by dominiklaubach** [comment]
FYI, checking the docs would have helped with this, too: http://panacodalabs.github.com/The-M-Docs/#espresso/native_packaging
