### ISSUE TITLE
folder incubator-cordova-android does not exist in the repo

### ISSUE THREAD

**Issue by colegatron** [mway-io/Espresso#110]
After a 'espresso package build android' I got a fail. Looking in the log appears: 
- cat /home/ivang/Mis_PortableApps/Espresso/package/../submodules/git-wip-us.apache.org/repos/asf/incubator-cordova-android/VERSION
  cat: /home/ivang/Mis_PortableApps/Espresso/package/../submodules/git-wip-us.apache.org/repos/asf/incubator-cordova-android/VERSION: File or folder does not exist

After check it, the incubator-cordova-ios does exist, but the android version does not.

**Comment by ghost** [comment]
Open these files package/Cordova/iOS/bin/setup-project package/Cordova/Android/bin/build and remove the word "incubator-".
