### ISSUE TITLE
Proxy corrupts png files

### ISSUE THREAD

**Issue by cwygoda** [mway-io/Espresso#12]
When trying to png files through the Espresso proxy corrupts them... File length is the same, but the content changes. Can anyone confirm this issue? Or is it some configuration I am missing?

Using Espresso 64dc39b37a3be27d9c4d3e31c3ec4cbf30499e97 (6/9/11 11:50 AM)

**Comment by sebastianwerler** [comment]
We'll work on this issue. Could be a file encoding problem... but not sure right now.
