### ISSUE TITLE
Espresso-1.0.0 tar.gz from the-m-project.org contains garbage

### ISSUE THREAD

**Issue by 4z3** [mway-io/Espresso#56]
The Espresso tar.gz-package contains files of the form ._*, you can find it with

```
find extracted-espresso-directory -name '._*'
```

These files prevent Espresso from working.  Please replace the download with a cleaned-up version ASAP.

You can cleanup the directory before tarring it with:

```
find extracted-espresso-directory -name '._*' -exec rm -v \{\} \;
```

**Comment by dominiklaubach** [comment]
As discussed on the IRC before, this happened due to a "bug" in Mac OSX's tarball generation. Sorry folks if you had any trouble based on this issue. The archive is fixed now and it won't happen again :)

Big THX to 4z3 for the instant support on this!!!

Best regards
Dominik
