### ISSUE TITLE
Warning: dropping manifest because typeof is neither string nor boolean.

### ISSUE THREAD

**Issue by volkert** [mway-io/Espresso#76]
If I want to package my build for android the following warning appears in line 1 of the package.log file:

<pre>Warning: dropping manifest because typeof is neither string nor boolean.</pre>

It looks like it skips all options for the activity section of android manifest but I wasn't able to verify this.

EDIT: I tried to package the Todos example app.

**Comment by 4z3** [comment]
This warning gets emitted by the configuration reader for each config.json property that doesn't get exported as environmental variable.

The wording could be improved or the warning could be filtered, but as package.log isn't intended for user-consumption it won't happen until we specify some component logging format.
