### ISSUE TITLE
Google Play needs the variable "minSdkVersion" in the file "AndroidManifest.xml"

### ISSUE THREAD

**Issue by siamak-haschemi** [mway-io/Espresso#80]
_Given_ I configured a android package decleration in config.json
_When_ I sign and build the android APK package
_Then_ the temporary created Android-Project should contain the "minSdkVersion" tag in the AndroidManifest.xml

File Espresso/package/PhoneGap/Android/setup-manifest needs to be changed

**Comment by siamak-haschemi** [comment]
I propose the addition of a new config.json parameter "minSdkVersion".

Here is the little patch for setup-manifest

https://gist.github.com/2730236

**Comment by siamak-haschemi** [comment]
Please reopen this Issue, since the new generic AndroidManifest approach (#87) does not contain the required mandatory _minSdkVersion_ property. Again, without that property I was not able to relase into the Google Play Store.

Thanks!

**Comment by 4z3** [comment]
The `minSdkVersion` property should be optional and default to some reasonable value.

Potential default values are at least:
- the version part of `package.{target}.sdk`, like done in 8fbd4ae0fbab64a9fa755654ce696060464c3e60
- `"1"`, which would conform to the Android Dev Guide's default value (see http://developer.android.com/guide/topics/manifest/uses-sdk-element.html).

**Comment by sebastianwerler** [comment]
I prefer conformity with the default that Android uses, means "1".

**Comment by dominiklaubach** [comment]
I'd recommend to set the default minimum sdk version to level 8 based on this: http://developer.android.com/resources/dashboard/platform-versions.html
