### ISSUE TITLE
ESPRESSO-DEBUG has no effect

### ISSUE THREAD

**Issue by siamak-haschemi** [mway-io/Espresso#84]
Espresso/package/PhoneGap/Android/build does not allow ispecting the native package

<pre>
...
if echo "${ESPRESSO_DEBUG-}" | grep -q package; then
...
</pre>

should be 

<pre>
...
if echo "${ESPRESSO_DEBUG-}" | grep -q ${package}; then
...
</pre>

**Comment by 4z3** [comment]
_Please note this debugging facility is an undocumented feature and subject to change._

Exporting `ESPRESSO_DEBUG=package` currently causes Espresso to preserve intermediate files while generating the package.

**Comment by siamak-haschemi** [comment]
OK, i got it wrong. Thank you for the clarification.
