### ISSUE TITLE
Add more configuration options for the AndroidManifest.xml

### ISSUE THREAD

**Issue by siamak-haschemi** [mway-io/Espresso#85]
Please add support for permissions, minSdkVersion, versionName, version, ...

See my proposal for permissions and minSdkVersion:

https://github.com/siamak-haschemi/Espresso/commit/e0f9e784598bc07c64531c6d86fddfbfe088cd70

**Comment by 4z3** [comment]
That's definitely a feature to be considered.  But we should aim for a solution, that allows arbitrary modifications to AndroidManifest.xml in a generalized way, so Espresso doesn't have to be extended whenever a new configuration option should be modifiable.
