### ISSUE TITLE
Extend the config.json documentation with the new generic way of manipulating the AndroidManifest.xml

### ISSUE THREAD

**Issue by siamak-haschemi** [mway-io/Espresso#88]
With the pull request #87, we introduced a generic way to manipulate the resulting AndroidManifest.xml. The [documentation of config.json](https://github.com/mwaylabs/Espresso/wiki/Config.json) has to be extended for that.

**Comment by 4z3** [comment]
The [config.json documentation](https://github.com/mwaylabs/Espresso/wiki/Config.json) is now up-to-date for the `"manifest"`. See [config.json; status: 2012-05-21](https://github.com/mwaylabs/Espresso/wiki/Config.json/83bfb6cc6a1ccdf205fd8f4604604f2bad4f52f7).
